const fs = require('fs');

const iconMapping = {
  Home: 'Mosque',
  HomeIcon: 'Mosque',
  Activity: 'ChartLineUp',
  AlertCircle: 'WarningCircle',
  ArrowLeft: 'ArrowLeft',
  ArrowRight: 'ArrowRight',
  Ban: 'Prohibit',
  BarChart: 'ChartBar',
  BarChart3: 'ChartBar',
  BarChartIcon: 'ChartBar',
  Bell: 'Bell',
  BellIcon: 'Bell',
  BellOff: 'BellSlash',
  Book: 'BookOpenText',
  BookIcon: 'BookOpenText',
  BookOpen: 'BookOpenText',
  BookOpenIcon: 'BookOpenText',
  BookOpenText: 'BookOpenText',
  BookText: 'BookOpenText',
  BookA: 'BookOpenText',
  BookType: 'BookOpenText',
  Calculator: 'Calculator',
  Calendar: 'CalendarBlank',
  CalendarBlank: 'CalendarBlank',
  CalendarCheck: 'CalendarCheck',
  CalendarDays: 'CalendarBlank',
  CalendarIcon: 'CalendarBlank',
  Check: 'Check',
  CheckCircle: 'CheckCircle',
  CheckCircle2: 'CheckCircle',
  CheckSquare: 'CheckSquare',
  ChevronDown: 'CaretDown',
  ChevronLeft: 'CaretLeft',
  ChevronRight: 'CaretRight',
  ChevronUp: 'CaretUp',
  Circle: 'Circle',
  Clock: 'Clock',
  Cloud: 'Cloud',
  CloudFog: 'CloudFog',
  CloudLightning: 'Lightning',
  CloudOff: 'CloudSlash',
  CloudRain: 'CloudRain',
  CloudSun: 'CloudSun',
  Coins: 'Coins',
  Copy: 'Copy',
  Database: 'Database',
  DeviceMobile: 'DeviceMobile',
  DocumentText: 'FileText',
  DollarSign: 'CurrencyDollar',
  Download: 'DownloadSimple',
  DownloadSimple: 'DownloadSimple',
  Edit2: 'PencilSimple',
  Edit3: 'PencilSimple',
  Envelope: 'Envelope',
  FileText: 'FileText',
  FloppyDisk: 'FloppyDisk',
  Gear: 'Gear',
  GearIcon: 'Gear',
  Globe: 'Globe',
  GlobeIcon: 'Globe',
  Handshake: 'Handshake',
  Heart: 'Heart',
  HeartHandshake: 'Handshake',
  HelpCircle: 'Question',
  History: 'ClockCounterClockwise',
  Image: 'Image',
  ImageIcon: 'Image',
  Info: 'Info',
  Landmark: 'Mosque',
  Languages: 'Translate',
  LanguagesIcon: 'Translate',
  Layers: 'Stack',
  LayoutDashboard: 'SquaresFour',
  Library: 'Books',
  Lightbulb: 'Lightbulb',
  Lightning: 'Lightning',
  List: 'List',
  Loader2: 'Spinner',
  Lock: 'ShieldCheck',
  LogOut: 'SignOut',
  Mail: 'Envelope',
  Map: 'MapTrifold',
  MapPin: 'MapPin',
  MapPinOff: 'MapPinLine',
  Menu: 'List',
  MessageCircle: 'ChatCircle',
  MessageSquare: 'ChatCircle',
  Minus: 'Minus',
  Moon: 'Moon',
  MoonStar: 'MoonStars',
  MoonStars: 'MoonStars',
  MoreVertical: 'DotsThreeVertical',
  Palette: 'Palette',
  Pause: 'Pause',
  Pencil: 'PencilSimple',
  Phone: 'Phone',
  Play: 'Play',
  Plus: 'Plus',
  Printer: 'Printer',
  Radio: 'SpeakerHigh',
  RefreshCw: 'ArrowsClockwise',
  RotateCcw: 'ArrowCounterClockwise',
  Save: 'FloppyDisk',
  Search: 'MagnifyingGlass',
  Send: 'PaperPlaneRight',
  Settings: 'Gear',
  Settings2: 'GearSix',
  Share2: 'ShareNetwork',
  ShareNetwork: 'ShareNetwork',
  ShieldAlert: 'ShieldWarning',
  ShieldCheck: 'ShieldCheck',
  ShieldWarning: 'ShieldWarning',
  Shirt: 'TShirt',
  ShoppingBag: 'ShoppingBag',
  Smartphone: 'DeviceMobile',
  Snowflake: 'Snowflake',
  Sparkle: 'Sparkle',
  Sparkles: 'Sparkle',
  Speaker: 'SpeakerHigh',
  SpeakerHigh: 'SpeakerHigh',
  SpeakerX: 'SpeakerX',
  Spinner: 'Spinner',
  Star: 'Star',
  Sun: 'Sun',
  SunMedium: 'SunHorizon',
  Sunrise: 'SunDim',
  Sunset: 'CloudSun',
  Target: 'Target',
  ThumbsUp: 'ThumbsUp',
  Trash: 'Trash',
  Trash2: 'Trash',
  TrendingUp: 'TrendUp',
  Trophy: 'Trophy',
  Undo2: 'ArrowUUpLeft',
  Upload: 'UploadSimple',
  UploadSimple: 'UploadSimple',
  User: 'User',
  UserCircle: 'User',
  UserIcon: 'User',
  Users: 'Users',
  Vibrate: 'Vibrate',
  Video: 'VideoCamera',
  Volume2: 'SpeakerHigh',
  VolumeX: 'SpeakerX',
  Warning: 'Warning',
  Wifi: 'WifiHigh',
  WifiOff: 'WifiSlash',
  X: 'X',
  XCircle: 'XCircle',

  PrayerTimesMosque: 'Mosque',
  Mosque: 'Mosque',
  MosqueIcon: 'Mosque',
  IslamicCalendar: 'CalendarBlank',
  HijriCalendarIcon: 'CalendarBlank',
  JantriBook: 'BookOpenText',
  CrescentMoon: 'Moon',
  CrescentMoonIcon: 'Moon',
  LanternCrescent: 'MoonStars',
  LanternCrescentIcon: 'MoonStars',
  TasbihBeads: 'DotsThreeCircle',
  TasbihIcon: 'DotsThreeCircle',
  PrayerBeads: 'DotsThreeCircle',
  CharityHand: 'HandCoins',
  CharityHandIcon: 'HandCoins',
  HandCoins: 'HandCoins',
  QiblaCompass: 'Compass',
  Compass: 'Compass',
  CompassIcon: 'Compass',
  CompassKaabaIcon: 'Compass',
  Kaaba: 'Cube',
  KaabaIcon: 'Cube',
  RaisedHands: 'HandsPraying',
  RaisedHandsIcon: 'HandsPraying',
  HandsPraying: 'HandsPraying',
  StarCrescent: 'StarAndCrescent',
  StarCrescentIcon: 'StarAndCrescent',
  StarAndCrescent: 'StarAndCrescent',
  CalendarBell: 'BellRinging',
  CalendarBellIcon: 'BellRinging',
  BellRinging: 'BellRinging',
  Scroll: 'Scroll',
  ScrollText: 'Scroll',
  QuranBook: 'BookBookmark',
  MosqueMapPin: 'MapPin',
  Bookmark: 'Bookmark',
  BookmarkIcon: 'Bookmark',
  AlarmClock: 'Alarm',
  AlertTriangle: 'Warning',
  Camera: 'Camera'
};

let fileContent = `import { forwardRef } from 'react';
import * as Phosphor from '@phosphor-icons/react';

export const LucideProps = Object; // Dummy type

const wrapIcon = (PhosphorIcon) => forwardRef(({ size = 24, strokeWidth, className, color, ...props }, ref) => {
  if (!PhosphorIcon) return null;
  return (
    <PhosphorIcon
      ref={ref}
      size={size}
      weight="duotone"
      className={className}
      color={color || 'currentColor'}
      {...props}
    />
  );
});

`;

for (const [exportName, phosphorName] of Object.entries(iconMapping)) {
  fileContent += `export const ${exportName} = wrapIcon(Phosphor.${phosphorName});\n`;
}

fs.writeFileSync('src/lib/icons.tsx', fileContent, 'utf8');
console.log('Done mapping icons');
