const fs = require('fs');

const iconMapping = {
  Home: '🕌',
  HomeIcon: '🕌',
  Activity: '📈',
  AlertCircle: '⚠️',
  ArrowLeft: '⬅️',
  ArrowRight: '➡️',
  Ban: '🚫',
  BarChart: '📊',
  BarChart3: '📊',
  BarChartIcon: '📊',
  Bell: '🔔',
  BellIcon: '🔔',
  BellOff: '🔕',
  Book: '📖',
  BookIcon: '📖',
  BookOpen: '📖',
  BookOpenIcon: '📖',
  BookOpenText: '📖',
  BookText: '📖',
  BookA: '📖',
  BookType: '📖',
  Calculator: '🧮',
  Calendar: '📅',
  CalendarBlank: '📅',
  CalendarCheck: '📅',
  CalendarDays: '📅',
  CalendarIcon: '📅',
  Check: '✅',
  CheckCircle: '✅',
  CheckCircle2: '✅',
  CheckSquare: '✅',
  ChevronDown: '⬇️',
  ChevronLeft: '⬅️',
  ChevronRight: '➡️',
  ChevronUp: '⬆️',
  Circle: '⏺️',
  Clock: '🕰️',
  Cloud: '☁️',
  CloudFog: '🌫️',
  CloudLightning: '🌩️',
  CloudOff: '☁️',
  CloudRain: '🌧️',
  CloudSun: '⛅',
  Coins: '💰',
  Copy: '📋',
  Database: '🗄️',
  DeviceMobile: '📱',
  DocumentText: '📄',
  DollarSign: '💲',
  Download: '⬇️',
  DownloadSimple: '⬇️',
  Edit2: '✏️',
  Edit3: '✏️',
  Envelope: '📧',
  FileText: '📄',
  FloppyDisk: '💾',
  Gear: '⚙️',
  GearIcon: '⚙️',
  Globe: '🌐',
  GlobeIcon: '🌐',
  Handshake: '🤝',
  Heart: '❤️',
  HeartHandshake: '🤝',
  HelpCircle: '❓',
  History: '🕰️',
  Image: '🖼️',
  ImageIcon: '🖼️',
  Info: 'ℹ️',
  Landmark: '🕌',
  Languages: '🌐',
  LanguagesIcon: '🌐',
  Layers: '📚',
  LayoutDashboard: '🎛️',
  Library: '📚',
  Lightbulb: '💡',
  Lightning: '⚡',
  List: '📝',
  Loader2: '⏳',
  Lock: '🔐',
  LogOut: '🚪',
  Mail: '📧',
  Map: '🗺️',
  MapPin: '📍',
  MapPinOff: '📍',
  Menu: '☰',
  MessageCircle: '💬',
  MessageSquare: '💬',
  Minus: '➖',
  Moon: '🌙',
  MoonStar: '🌙',
  MoonStars: '🌙',
  MoreVertical: '⋮',
  Palette: '🎨',
  Pause: '⏸️',
  Pencil: '✏️',
  Phone: '📞',
  Play: '▶️',
  Plus: '➕',
  Printer: '🖨️',
  Radio: '📻',
  RefreshCw: '🔄',
  RotateCcw: '↺',
  Save: '💾',
  Search: '🔍',
  Send: '🚀',
  Settings: '⚙️',
  Settings2: '⚙️',
  Share2: '📤',
  ShareNetwork: '📤',
  ShieldAlert: '🛡️',
  ShieldCheck: '🛡️',
  ShieldWarning: '🛡️',
  Shirt: '👕',
  ShoppingBag: '🛍️',
  Smartphone: '📱',
  Snowflake: '❄️',
  Sparkle: '✨',
  Sparkles: '✨',
  Speaker: '🎙️',
  SpeakerHigh: '🔊',
  SpeakerX: '🔇',
  Spinner: '⏳',
  Star: '⭐',
  Sun: '☀️',
  SunMedium: '⛅',
  Sunrise: '🌅',
  Sunset: '🌇',
  Target: '🎯',
  ThumbsUp: '👍',
  Trash: '🗑️',
  Trash2: '🗑️',
  TrendingUp: '📈',
  Trophy: '🏆',
  Undo2: '↩️',
  Upload: '⬆️',
  UploadSimple: '⬆️',
  User: '👤',
  UserCircle: '👤',
  UserIcon: '👤',
  Users: '👥',
  Vibrate: '📳',
  Video: '📹',
  Volume2: '🔊',
  VolumeX: '🔇',
  Warning: '⚠️',
  Wifi: '📶',
  WifiOff: '📴',
  X: '❌',
  XCircle: '❌',

  PrayerTimesMosque: '🕌',
  Mosque: '🕌',
  MosqueIcon: '🕌',
  IslamicCalendar: '📅',
  HijriCalendarIcon: '📅',
  JantriBook: '📖',
  CrescentMoon: '🌙',
  CrescentMoonIcon: '🌙',
  LanternCrescent: '🏮',
  LanternCrescentIcon: '🏮',
  TasbihBeads: '📿',
  TasbihIcon: '📿',
  PrayerBeads: '📿',
  CharityHand: '💰',
  CharityHandIcon: '💰',
  HandCoins: '💰',
  QiblaCompass: '🧭',
  Compass: '🧭',
  CompassIcon: '🧭',
  CompassKaabaIcon: '🧭',
  Kaaba: '🕋',
  KaabaIcon: '🕋',
  RaisedHands: '🤲',
  RaisedHandsIcon: '🤲',
  HandsPraying: '🤲',
  StarCrescent: '⭐',
  StarCrescentIcon: '⭐',
  StarAndCrescent: '⭐',
  CalendarBell: '🔔',
  CalendarBellIcon: '🔔',
  BellRinging: '🔔',
  Scroll: '📜',
  ScrollText: '📜',
  QuranBook: '📖',
  MosqueMapPin: '🕌',
  Bookmark: '🔖',
  BookmarkIcon: '🔖',
  AlarmClock: '⏰',
  AlertTriangle: '⚠️',
  Camera: '📷',
  DotsThreeCircle: '📿'
};

let fileContent = `import { forwardRef } from 'react';

export const LucideProps = Object; // Dummy type

const wrapEmoji = (emoji) => forwardRef(({ size = 24, strokeWidth, className, color, ...props }, ref) => {
  return (
    <span
      ref={ref}
      style={{ fontSize: size, lineHeight: 1, display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}
      className={className}
      {...props}
    >
      {emoji}
    </span>
  );
});

`;

for (const [exportName, emoji] of Object.entries(iconMapping)) {
  fileContent += `export const ${exportName} = wrapEmoji('${emoji}');\n`;
}

fs.writeFileSync('src/lib/icons.tsx', fileContent, 'utf8');
console.log('Done mapping emoji icons');
